# Generated by Django 5.2.2 on 2025-08-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=25)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
